apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: analytics-processor-8184
  namespace: MendPerformance
  annotations:
    github.com/project-slug: MendPerformance/analytics-processor-8184
spec:
  type: service
  lifecycle: unknown
  owner: mend.io
